#!/bin/bash
#
# handle unexistant uppercase commands by swearing
# (C) TTFYW by Gabriele "Asbesto" Zaverio, 2019 
# install in /usr/lib/command-not-found. It use the
# standard behaviour for command not found in bash and, 
# I think, zsh. man bash for details ;)
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.
#
# USAGE: 
#        install this script in /usr/lib/command-not-found and 
#        make it executable. 
#

if [ "$2" == "${2^^}" ]; then
   echo AOOOOOH MA CHE CAZZO URLI
   else
   echo $2: command not found, `unodi \
    "TESTA DI CAZZO" \
    "COGLIONE" \
    "IMBECILLE" \
    "FIGLIO DI PUTTANA" \
    "SUCCHIACAZZI DI MERDA" \
    "DEFICIENTE PATENTATO" \
    "PEZZO DI MERDA" \
    "MINCHIONE" \
    "TESTA DI MINCHIA" \
    "FIGLIO DI GRAN TROIA" \
    "IDIOTA" \
    "CRETINO" \
    "SCEMO DI GUERRA" \
    "TESTA DI GRAN CAZZO" \
    "STUPIDO IDIOTA" \
    "COGLIONAZZO" \
    "FACCIA DI CAZZO" \
    "FACCIA DI MERDA" \
    "FACCIA DI MINCHIA" \
    "SUCAMINCHIA DEGLI DEI" \
    "PUTTANA IMPERIALE" \
    "TROIONE IMMENSO" \
    "CAZZONE"`

fi
