.\"	$NetBSD: random.6,v 1.3 1997/10/12 01:14:18 lukem Exp $
.Dd July 11, 1999
.Dt UNODI 1
.Os Linux 4
.Sh NAME
.Nm unodi
.Nd output one command-line argument, chosen at random
.Sh SYNOPSIS
.Nm
.Ar arg1
.Op Ar arg2...
.Sh DESCRIPTION
.Nm
copies one of its command-line arguments, chosen at random and with
equal probability, to standard output.
Calling
.Nm
with no parameters is an error.
.Sh SEE ALSO
.Xr random 6
